In [1]:
import pandas as pd

In [3]:
data = {
    'age': [25,35,45,23,54,28,32,42,37],
    'salary': [5000,6000,10000,4000,12000,35000,110000,6500,9500],
    'Purchase Amount': [200,500,700,150,800,300,750,400,650]
}

df = pd.DataFrame(data)
df

   age  salary  Purchase Amount
0   25    5000              200
1   35    6000              500
2   45   10000              700
3   23    4000              150
4   54   12000              800
5   28   35000              300
6   32  110000              750
7   42    6500              400
8   37    9500              650

In [4]:
df.describe()

             age         salary  Purchase Amount
count   9.000000       9.000000         9.000000
mean   35.666667   22000.000000       494.444444
std    10.074721   34319.273011       244.239181
min    23.000000    4000.000000       150.000000
25%    28.000000    6000.000000       300.000000
50%    35.000000    9500.000000       500.000000
75%    42.000000   12000.000000       700.000000
max    54.000000  110000.000000       800.000000

In [5]:
#Normalizing the dataset
normalized_df = (df-df.min())/(df.max()-df.min())
normalized_df

        age    salary  Purchase Amount
0  0.064516  0.009434         0.076923
1  0.387097  0.018868         0.538462
2  0.709677  0.056604         0.846154
3  0.000000  0.000000         0.000000
4  1.000000  0.075472         1.000000
5  0.161290  0.292453         0.230769
6  0.290323  1.000000         0.923077
7  0.612903  0.023585         0.384615
8  0.451613  0.051887         0.769231

In [6]:
normalized_df.describe()

            age    salary  Purchase Amount
count  9.000000  9.000000         9.000000
mean   0.408602  0.169811         0.529915
std    0.324991  0.323767         0.375753
min    0.000000  0.000000         0.000000
25%    0.161290  0.018868         0.230769
50%    0.387097  0.051887         0.538462
75%    0.612903  0.075472         0.846154
max    1.000000  1.000000         1.000000

In [7]:
#Standardizing the dataset
standardized_df = (df-df.mean())/df.std()
standardized_df

        age    salary  Purchase Amount
0 -1.058756 -0.495348        -1.205558
1 -0.066172 -0.466210         0.022746
2  0.926411 -0.349658         0.841616
3 -1.257272 -0.524487        -1.410275
4  1.819736 -0.291381         1.251051
5 -0.760981  0.378796        -0.796123
6 -0.363947  2.564157         1.046333
7  0.628636 -0.451641        -0.386688
8  0.132344 -0.364227         0.636898

In [8]:
standardized_df.describe()

                age        salary  Purchase Amount
count  9.000000e+00  9.000000e+00     9.000000e+00
mean   2.343804e-16  1.233581e-17    -6.167906e-17
std    1.000000e+00  1.000000e+00     1.000000e+00
min   -1.257272e+00 -5.244866e-01    -1.410275e+00
25%   -7.609806e-01 -4.662103e-01    -7.961231e-01
50%   -6.617222e-02 -3.642268e-01     2.274637e-02
75%    6.286361e-01 -2.913815e-01     8.416158e-01
max    1.819736e+00  2.564157e+00     1.251051e+00